spring:
  cloud:
    stream:
      default:
        consumer:
          headerMode: raw
      kafka:
        binder:
          zkNodes: localhost
          brokers: localhost
          zkSessionTimeout: 20000
          zkConnectionTimeout: 20000