server:
  port: 8006
spring:
  thymeleaf.mode: LEGACYHTML5
  mail:
    host: smtp.gmail.com
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls.enable: true
app.login.url: http://localhost:4200/login
monitoring:
  matchers:
    - name: api.user
      method: POST
      matcher: /api/user
    - name: prometheus
      method: GET
      matcher: /prometheus
    - name: metrics
      method: GET
      matcher: /metrics