server:
  port: 8005
eureka:
  instance:
    statusPageUrlPath: /info
    healthCheckUrlPath: /health
zuul:
  routes:
    profile-service:
      prefix: /profile
    blog-service:
      prefix: /blog
    uaa-service:
      prefix: /uaa